# Generated by Django 5.2.9 on 2025-12-30 10:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estates', '0001_initial'),
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Fee name (e.g., 'Security Levy 2025')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional detailed description')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Fee amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this fee', on_delete=django.db.models.deletion.PROTECT, related_name='created_fees', to=settings.AUTH_USER_MODEL)),
                ('estate', models.ForeignKey(help_text='Estate this fee belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='estates.estate')),
            ],
            options={
                'verbose_name': 'Fee',
                'verbose_name_plural': 'Fees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', help_text='Payment status', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee', models.ForeignKey(help_text='The fee being assigned', on_delete=django.db.models.deletion.CASCADE, related_name='fee_assignments', to='payments.fee')),
                ('unit', models.ForeignKey(help_text='The unit this fee applies to', on_delete=django.db.models.deletion.CASCADE, related_name='fee_assignments', to='units.unit')),
            ],
            options={
                'verbose_name': 'Fee Assignment',
                'verbose_name_plural': 'Fee Assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], help_text='Method of payment', max_length=20)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When the payment was made')),
                ('reference_number', models.CharField(blank=True, help_text='Optional payment reference (e.g., transaction ID)', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Optional payment notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_assignment', models.OneToOneField(help_text='The fee assignment this payment is for', on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='payments.feeassignment')),
                ('recorded_by', models.ForeignKey(help_text='User who recorded this payment', on_delete=django.db.models.deletion.PROTECT, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(help_text='Unique receipt number (auto-generated)', max_length=50, unique=True)),
                ('estate_name', models.CharField(help_text='Estate name (cached for receipt)', max_length=255)),
                ('unit_identifier', models.CharField(help_text='Unit identifier (cached for receipt)', max_length=100)),
                ('fee_name', models.CharField(help_text='Fee name (cached for receipt)', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid (cached for receipt)', max_digits=12)),
                ('payment_date', models.DateTimeField(help_text='Payment date (cached for receipt)')),
                ('payment_method', models.CharField(help_text='Payment method (cached for receipt)', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(help_text='The payment this receipt is for', on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['estate', '-created_at'], name='payments_fe_estate__b06a70_idx'),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['due_date'], name='payments_fe_due_dat_17fadb_idx'),
        ),
        migrations.AddIndex(
            model_name='feeassignment',
            index=models.Index(fields=['fee', 'status'], name='payments_fe_fee_id_69fed7_idx'),
        ),
        migrations.AddIndex(
            model_name='feeassignment',
            index=models.Index(fields=['unit', 'status'], name='payments_fe_unit_id_88f123_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feeassignment',
            unique_together={('fee', 'unit')},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['-payment_date'], name='payments_pa_payment_60e7bc_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['fee_assignment'], name='payments_pa_fee_ass_d54b0c_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['receipt_number'], name='payments_re_receipt_8aa2fc_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['-issued_at'], name='payments_re_issued__548047_idx'),
        ),
    ]
