"""
Models for documents app.

Handles system-generated PDF documents including payment receipts and announcements.
"""

import uuid
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import FileExtensionValidator
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class DocumentType(models.TextChoices):
    """Types of system-generated documents."""
    
    PAYMENT_RECEIPT = 'payment_receipt', _('Payment Receipt')
    ANNOUNCEMENT = 'announcement', _('Announcement')


class DocumentStatus(models.TextChoices):
    """Status of document generation."""
    
    PENDING = 'pending', _('Pending')
    GENERATING = 'generating', _('Generating')
    COMPLETED = 'completed', _('Completed')
    FAILED = 'failed', _('Failed')


class Document(models.Model):
    """
    Represents a system-generated PDF document.
    
    Stores payment receipts and printable announcements. All documents
    are generated by the system and not uploaded by users.
    """
    
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    document_type = models.CharField(
        max_length=50,
        choices=DocumentType.choices,
        db_index=True,
        help_text=_('Type of document')
    )
    title = models.CharField(
        max_length=255,
        help_text=_('Document title')
    )
    file = models.FileField(
        upload_to='documents/%Y/%m/%d/',
        validators=[FileExtensionValidator(allowed_extensions=['pdf'])],
        null=True,
        blank=True,
        help_text=_('PDF file')
    )
    status = models.CharField(
        max_length=20,
        choices=DocumentStatus.choices,
        default=DocumentStatus.PENDING,
        db_index=True,
        help_text=_('Document generation status')
    )
    
    # Related entities (flexible for different document types)
    related_user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='documents',
        null=True,
        blank=True,
        db_index=True,
        help_text=_('User this document is for')
    )
    related_payment_id = models.UUIDField(
        null=True,
        blank=True,
        db_index=True,
        help_text=_('Related payment ID for receipts')
    )
    related_announcement_id = models.UUIDField(
        null=True,
        blank=True,
        db_index=True,
        help_text=_('Related announcement ID')
    )
    
    # Metadata
    file_size = models.PositiveIntegerField(
        null=True,
        blank=True,
        help_text=_('File size in bytes')
    )
    metadata = models.JSONField(
        default=dict,
        blank=True,
        help_text=_('Additional metadata for document generation')
    )
    error_message = models.TextField(
        blank=True,
        help_text=_('Error message if generation failed')
    )
    
    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField(auto_now=True)
    generated_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text=_('When the document was successfully generated')
    )
    
    # Soft delete
    is_deleted = models.BooleanField(default=False, db_index=True)
    deleted_at = models.DateTimeField(null=True, blank=True)
    
    class Meta:
        ordering = ['-created_at']
        verbose_name = _('Document')
        verbose_name_plural = _('Documents')
        indexes = [
            models.Index(fields=['document_type', 'status']),
            models.Index(fields=['related_user', 'document_type']),
            models.Index(fields=['-created_at']),
        ]
    
    def __str__(self):
        return f"{self.get_document_type_display()} - {self.title}"
    
    def clean(self):
        """Validate model data."""
        from django.core.exceptions import ValidationError
        
        if self.document_type == DocumentType.PAYMENT_RECEIPT and not self.related_payment_id:
            raise ValidationError({
                'related_payment_id': _('Payment receipts must have a related payment ID')
            })
        
        if self.document_type == DocumentType.ANNOUNCEMENT and not self.related_announcement_id:
            raise ValidationError({
                'related_announcement_id': _('Announcements must have a related announcement ID')
            })
        
        if self.status == DocumentStatus.COMPLETED and not self.file:
            raise ValidationError({
                'file': _('Completed documents must have a file')
            })


class DocumentDownload(models.Model):
    """
    Tracks document downloads for analytics and audit purposes.
    """
    
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    document = models.ForeignKey(
        Document,
        on_delete=models.CASCADE,
        related_name='downloads',
        db_index=True
    )
    user = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        related_name='document_downloads',
        db_index=True,
        help_text=_('User who downloaded the document')
    )
    ip_address = models.GenericIPAddressField(
        null=True,
        blank=True,
        help_text=_('IP address of downloader')
    )
    user_agent = models.TextField(
        blank=True,
        help_text=_('Browser user agent')
    )
    downloaded_at = models.DateTimeField(auto_now_add=True, db_index=True)
    
    class Meta:
        ordering = ['-downloaded_at']
        verbose_name = _('Document Download')
        verbose_name_plural = _('Document Downloads')
        indexes = [
            models.Index(fields=['document', '-downloaded_at']),
            models.Index(fields=['user', '-downloaded_at']),
        ]
    
    def __str__(self):
        return f"{self.document.title} - {self.downloaded_at.strftime('%Y-%m-%d %H:%M')}"