# Generated by Django 5.2.9 on 2026-02-28 05:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.CharField(help_text='Unit identifier (e.g., House 12, Flat B3, Unit 205)', max_length=100)),
                ('unit_type', models.CharField(choices=[('HOUSE', 'House'), ('FLAT', 'Flat'), ('APARTMENT', 'Apartment'), ('STUDIO', 'Studio'), ('OTHER', 'Other')], default='FLAT', help_text='Type of property unit', max_length=20)),
                ('occupant_name', models.CharField(blank=True, help_text='Name of current occupant (free text)', max_length=200, null=True)),
                ('occupant_phone', models.CharField(blank=True, help_text='Contact phone number for occupant', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('description', models.TextField(blank=True, help_text='Additional notes or description about the unit', null=True)),
                ('is_occupied', models.BooleanField(default=False, help_text='Whether the unit is currently occupied')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the unit is active in the system')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estate', models.ForeignKey(help_text='Estate this unit belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='estates.estate')),
                ('owner', models.ForeignKey(help_text='User who owns or manages this unit', on_delete=django.db.models.deletion.PROTECT, related_name='owned_units', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['identifier'],
                'indexes': [models.Index(fields=['owner', 'is_active'], name='units_unit_owner_i_6f05a6_idx'), models.Index(fields=['identifier'], name='units_unit_identif_fdd1d6_idx'), models.Index(fields=['is_occupied'], name='units_unit_is_occu_26ac61_idx'), models.Index(fields=['estate', 'is_active'], name='units_unit_estate__17cdba_idx'), models.Index(fields=['estate', 'is_occupied'], name='units_unit_estate__06698d_idx')],
                'constraints': [models.UniqueConstraint(fields=('estate', 'identifier'), name='unique_unit_identifier_per_estate')],
            },
        ),
    ]
