# Generated by Django 5.2.9 on 2025-12-30 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0001_initial'),
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='unit',
            name='unique_unit_identifier_per_owner',
        ),
        migrations.AddField(
            model_name='unit',
            name='estate',
            field=models.ForeignKey(help_text='Estate this unit belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='estates.estate'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['estate', 'is_active'], name='units_unit_estate__17cdba_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['estate', 'is_occupied'], name='units_unit_estate__06698d_idx'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('estate', 'identifier'), name='unique_unit_identifier_per_estate'),
        ),
    ]
