# Generated by Django 5.2.9 on 2025-12-30 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0001_initial'),
        ('units', '0002_remove_unit_unique_unit_identifier_per_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='estate',
            field=models.ForeignKey(help_text='Estate this unit belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='estates.estate'),
        ),
    ]
