# Generated by Django 5.2.9 on 2025-12-28 21:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the estate', max_length=255)),
                ('estate_type', models.CharField(choices=[('GOVERNMENT', 'Government'), ('PRIVATE', 'Private')], default='PRIVATE', help_text='Ownership type of the estate (informational only in MVP)', max_length=20)),
                ('approximate_units', models.PositiveIntegerField(blank=True, help_text='Approximate number of units in the estate', null=True)),
                ('fee_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', help_text='How often estate fees are collected', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the estate is currently active')),
                ('description', models.TextField(blank=True, help_text='Optional description of the estate', null=True)),
                ('address', models.TextField(blank=True, help_text='Physical address of the estate', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estate',
                'verbose_name_plural': 'Estates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='estates_est_is_acti_4cf8dc_idx'), models.Index(fields=['estate_type'], name='estates_est_estate__ddf721_idx')],
            },
        ),
    ]
