# Generated by Django 5.2.9 on 2026-02-17 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0003_alter_estate_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='manager',
            field=models.OneToOneField(help_text='Estate manager responsible for this estate', on_delete=django.db.models.deletion.CASCADE, related_name='estate', to=settings.AUTH_USER_MODEL),
        ),
    ]
