# Generated by Django 5.2.9 on 2026-01-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ESTATE_MANAGER', 'Estate Manager'), ('REGULAR', 'Regular')], db_index=True, default='ESTATE_MANAGER', max_length=20),
        ),
    ]
