# Generated by Django 5.2.9 on 2026-01-13 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('estates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='estate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='estates.estate'),
        ),
    ]
