# Generated by Django 5.2.9 on 2026-01-14 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_estate'),
        ('estates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='estates.estate'),
        ),
    ]
