# Generated by Django 5.2.9 on 2026-02-03 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_estate'),
        ('estates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='estate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estates.estate'),
        ),
    ]
