# Generated by Django 5.2.9 on 2026-02-17 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_estate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='estate',
        ),
    ]
