# Generated by Django 5.2.9 on 2026-01-01 20:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('payment_receipt', 'Payment Receipt'), ('announcement', 'Announcement')], db_index=True, help_text='Type of document', max_length=50)),
                ('title', models.CharField(help_text='Document title', max_length=255)),
                ('file', models.FileField(blank=True, help_text='PDF file', null=True, upload_to='documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Document generation status', max_length=20)),
                ('related_payment_id', models.UUIDField(blank=True, db_index=True, help_text='Related payment ID for receipts', null=True)),
                ('related_announcement_id', models.UUIDField(blank=True, db_index=True, help_text='Related announcement ID', null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for document generation')),
                ('error_message', models.TextField(blank=True, help_text='Error message if generation failed')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_at', models.DateTimeField(blank=True, help_text='When the document was successfully generated', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('related_user', models.ForeignKey(blank=True, help_text='User this document is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentDownload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of downloader', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='documents.document')),
                ('user', models.ForeignKey(help_text='User who downloaded the document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Download',
                'verbose_name_plural': 'Document Downloads',
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type', 'status'], name='documents_d_documen_80b3b1_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['related_user', 'document_type'], name='documents_d_related_a4bb6e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-created_at'], name='documents_d_created_71dced_idx'),
        ),
        migrations.AddIndex(
            model_name='documentdownload',
            index=models.Index(fields=['document', '-downloaded_at'], name='documents_d_documen_c711b0_idx'),
        ),
        migrations.AddIndex(
            model_name='documentdownload',
            index=models.Index(fields=['user', '-downloaded_at'], name='documents_d_user_id_41bea9_idx'),
        ),
    ]
