# Generated by Django 5.2.9 on 2026-01-01 08:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Brief, descriptive title for the announcement', max_length=200)),
                ('message', models.TextField(help_text='Full announcement content')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this announcement is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Manager who created this announcement', on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='announcemen_created_da46df_idx'), models.Index(fields=['created_by', '-created_at'], name='announcemen_created_5c28e0_idx'), models.Index(fields=['is_active', '-created_at'], name='announcemen_is_acti_b68c9c_idx')],
            },
        ),
    ]
