# Generated by Django 5.2.9 on 2026-02-16 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_estate_and_more'),
        ('estates', '0003_alter_estate_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='estate',
            field=models.ForeignKey(help_text='Estate this announcement belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='estates.estate'),
        ),
    ]
