# Generated by Django 5.2.9 on 2026-01-01 07:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estates', '0001_initial'),
        ('units', '0003_alter_unit_estate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Brief title describing the issue', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the maintenance issue')),
                ('category', models.CharField(choices=[('WATER', 'Water'), ('ELECTRICITY', 'Electricity'), ('SECURITY', 'Security'), ('WASTE', 'Waste'), ('OTHER', 'Other')], db_index=True, default='OTHER', help_text='Category of the maintenance issue', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], db_index=True, default='OPEN', help_text='Current status of the ticket', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Timestamp when ticket was resolved', null=True)),
                ('created_by', models.ForeignKey(help_text='Estate manager who created this ticket', on_delete=django.db.models.deletion.PROTECT, related_name='created_maintenance_tickets', to=settings.AUTH_USER_MODEL)),
                ('estate', models.ForeignKey(help_text='Estate where this issue is located', on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_tickets', to='estates.estate')),
                ('unit', models.ForeignKey(blank=True, help_text='Optional unit associated with this issue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tickets', to='units.unit')),
            ],
            options={
                'verbose_name': 'Maintenance Ticket',
                'verbose_name_plural': 'Maintenance Tickets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['estate', 'status'], name='maintenance_estate__0454a2_idx'), models.Index(fields=['estate', 'category'], name='maintenance_estate__1919f9_idx'), models.Index(fields=['created_by', 'status'], name='maintenance_created_1187fe_idx')],
            },
        ),
    ]
